name: Test

on: [ push ]

jobs:
test:
  # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4
      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # запускаем тесты
      - run: ./gradlew clean test